name: Deploy Website to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload website files
        uses: azure/cli@v2
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name cloudresumemaurice01 \
              --destination '$web' \
              --source . \
              --pattern "*.html" \
              --overwrite \
              --auth-mode login

            az storage blob upload-batch \
              --account-name cloudresumemaurice01 \
              --destination '$web' \
              --source . \
              --pattern "*.css" \
              --overwrite \
              --auth-mode login